### ISSUE TITLE
Vibration support?

### ISSUE THREAD

**Issue by pmsobrado** [isage/vixen#10]
Does this plugin support vibration? I'm using a Logitech F710 and it works OK, but vibration is not working (tested with VitEsIn and PS1 games through Adrenaline).

Thanks.

**Comment by isage** [comment]
It does (works with f510 and logitech rumblepad), but f710 might require different custom rumble command.
Which mode are you using, btw, xinput or dinput?

**Comment by pmsobrado** [comment]
Xinput, I did not try Dinput.

**Comment by pmsobrado** [comment]
BTW, I'm using a PS Vita. I just thought that vibration may only work on PSTV.

**Comment by isage** [comment]
Nah, vibration works fine on vita with f510 and xbox360

**Comment by pmsobrado** [comment]
Cool :)

**Comment by isage** [comment]
[vixen.zip](https://github.com/isage/vixen/files/12182080/vixen.zip)
try this one

**Comment by pmsobrado** [comment]
Rumble works now in Vitesin, thanks. But it doesn't seem to work on Adrenaline and PS1 games. Is this normal? Is it only for native Vita games? Is there a PS Vita game with rumble I could try?

**Comment by isage** [comment]
I don't think there's any native vita game with rumble. It should work in adrenaline+ps1, check adrenaline/pspemu settings

**Comment by pmsobrado** [comment]
I don't see any rumble settings on Adrenaline, anything specific? Or maybe is it because my Vita doesn't report as a PSTV?

**Comment by isage** [comment]
Okay, so, make sure you have "use ds3/ds4" enabled in adrenaline settings. Make sure vibration is enabled in game option.
It looks like even with ds3 it's wonky. For example, it works in CTR, but i can't get it to work in Guilty Gear.

**Comment by pmsobrado** [comment]
Still not working. No rumble options whatsoever on Adrenaline (they appear if I use MiniVitaTV to transform my Vita to a PSTV). I'm gonna try a few games. I'm not using MiniVitaTV for now.

I don't have much PS1 games, but for me no one has vibration :(

**Comment by isage** [comment]
I'm pretty sure it won't work without minivitatv. Even ds3 rumble doesn't work without it.

**Comment by pmsobrado** [comment]
Ohh I see, MiniVitaTV HAS to be enabled. I will try it, thanks.

EDIT

The controller doesn't seem to work until I start configuring it on Vixen Helper. But with MiniVitaTV enabled, Vixen Helper hangs.

EDIT 2

Got it working. Bloody Roar 2 did not work, but Jackie Chan Stuntmaster did. Thanks! Will you update the current release?

**Comment by isage** [comment]
yep. a little later.

**Comment by pmsobrado** [comment]
Great, thanks for all!
