### ISSUE TITLE
Please add support for PS2 to PC usb adapter

### ISSUE THREAD

**Issue by olbaid** [isage/vixen#4]
This is an adapter that can convert PS2 dualshock to PC
USB Joystick (Vendor: 0e8f Product: 0003)
Name on adapter is "PIII Converter Model: 538"

Attached vixen.txt file from using vixen-helper on pstv.
[vixen.txt](https://github.com/isage/vixen/files/11178383/vixen.txt)

**Comment by isage** [comment]
[test.zip](https://github.com/isage/vixen/files/11198350/test.zip)
Try this, plugin with test support and app to test all inputs.

**Comment by olbaid** [comment]
Using the plugin in the zip file.
When I plug in the controller, I get a message on top left "This device is not supported."

Pressing L+R+Start also doesn't do anything

**Comment by isage** [comment]
[vixen.zip](https://github.com/isage/vixen/files/11208977/vixen.zip)
sorry, forgot to add it to supported devices list. try that one

**Comment by olbaid** [comment]
It works, thanks so much.

**Comment by olbaid** [comment]
@isage Made a mistake when verifying all the inputs with the test plugin.  Right analog stick left/right direction was up/down and vice versa.
Opened a pull request to fix it. https://github.com/isage/vixen/pull/6

I built the plugin locally and tested it on pstv.
