### ISSUE TITLE
please add support for "NES/FC/SFC Joypad TO USB BOX" (Vendor: 0079 Product: 1804)

### ISSUE THREAD

**Issue by vichorx** [isage/vixen#5]
Hello, thank you for the plugin, it's awesome. 
I was wondering if it's possible to add this adapter for SNES controllers (so no home or L2/R2 buttons o analogs). It's sold by Mayflash.

Thanks

[vixen.txt](https://github.com/isage/vixen/files/11298768/vixen.txt)

**Comment by isage** [comment]
[vixen.zip](https://github.com/isage/vixen/files/11305232/vixen.zip)
try that one

**Comment by vichorx** [comment]
It seems I screwed the recording of select and start as they're inverted, meaning that when you press start in the snes controller it's recognized as select and the same happens for select being recognized as start. 
All other buttons work without problem.

**Comment by isage** [comment]
Nah, i looks like i screwed up
try this one
[vixen.zip](https://github.com/isage/vixen/files/11307914/vixen.zip)

**Comment by vichorx** [comment]
Awesome. It works without a problem. 
Thank you very much
