### ISSUE TITLE
Hori -Project DIVA- X HD

### ISSUE THREAD

**Issue by Null-39** [isage/vixen#9]
[vixen-ps4.txt](https://github.com/isage/vixen/files/11760306/vixen-ps4.txt)

[vixen-ps3.txt](https://github.com/isage/vixen/files/11760299/vixen-ps3.txt)

**Comment by isage** [comment]
[vixen.zip](https://github.com/isage/vixen/files/11760894/vixen.zip)
try that one

**Comment by Null-39** [comment]
PS4 mode works great but in PS3 mode r2 is wrongly mapped to l2. This also affects the hori diva mini mapping.

**Comment by isage** [comment]
[vixen.zip](https://github.com/isage/vixen/files/11767597/vixen.zip)
